In [6]:
"""  
Here we test the Singleton pattern in Python that restricts the instantiation of a class to one single instance
"""

class Singleton:
    _instance = None  # Class attribute to store the singleton instance
    _is_initialized = False  # Class attribute to store the initialization state
    def __new__(cls):
        if cls._instance is None:
            print("Creating the instance")
            cls._instance = super(Singleton, cls).__new__(cls)
        return cls._instance

    def __init__(self):
        if self._is_initialized:
            print("Instance already initialized")
            return
        # Initialization method might be called multiple times
        # when attempting to create more instances
        print("Initializing the instance")
        self._is_initialized = True

# Usage of the Singleton class
singleton1 = Singleton()
singleton2 = Singleton()

# Check if both variables point to the same instance
print("Singleton1 is singleton2:", singleton1 is singleton2)

# Output additional instance properties or states to show it's the same instance
print("ID of singleton1:", id(singleton1))
print("ID of singleton2:", id(singleton2))

# self._is_initialized is True for singleton2 too because it's the same/only instance

Creating the instance
Initializing the instance
Instance already initialized
Singleton1 is singleton2: True
ID of singleton1: 140648641047120
ID of singleton2: 140648641047120


In [1]:
"""  
Here we test the input type of defaultdict, it should be a callable object/function
"""

from collections import defaultdict

class myclass:
    __slots__ = ['a', 'b']
    def __init__(self):
        self.a = 1
        self.b = 2
        # self.c = 3 it will raise an error because c is not in __slots__
    def __getitem__(self, key):
        return getattr(self, key)

a=defaultdict(myclass)
print(a['1'])
print(int())


0


In [2]:
"""  
Here we test generator usage with contextlib.contextmanager
"""

import contextlib

@contextlib.contextmanager
def open_file(path, mode):
    f = open(path, mode)
    try:            #using return instead of yield will cause an error
        yield f   # temporarily return the file object to the caller, will continue after the outer block is finished
    finally:      # Ensure the file is always closed under all circumstances, even exceptions or errors occur
        f.close()  # try-except will also work here, but need to specify the exception type

@contextlib.contextmanager
def open_file2(path, mode):
    with open(path, mode) as f:
        print("File opened")
        #return f  # must use yield here, otherwise the file will be closed before the caller can use it, causing an error
        yield f
# Usage
with open_file2("example.txt", "w") as file:
    file.write("Hello, world!")
    # raise Exception("An error occurred while writing to the file")
# The file is automatically closed here.

File opened


In [37]:
"""  
Here we test the output range of np.random.default_rng().integers()
"""

import numpy as np
rng = np.random.default_rng(0)
noops=0
print(rng.integers(noops + 1))

rng2=np.random.default_rng(42)  # if the seed is the same, the output will be the same
                                # if the seed is None, the output will be different
print(rng2.integers( range(1, noops + 16)))


0
[ 0  0  2  2  2  2  6  0  6  2  1  6 12 10 11]


In [4]:
"""  
Here we test whether class-level attributes are shared among instances of the same class.
and instance-level modification will not affect other instances
"""
from threading import Lock
class MyClassLock:
    lock=Lock()

class1 = MyClassLock()
class2 = MyClassLock()
print(class1.lock is class2.lock)   # whether the same lock object
class1.lock=1          # instance-level modification will not affect other instances
print(class2.lock)
print(class1.lock is class2.lock)

True
<unlocked _thread.lock object at 0x7feb50626300>
False


In [10]:
# Python first looks for the attribute in the instance's namespace. 
# If it doesn't find it there, Python then looks in the class namespace. 

class MyClass:
    shared_var = 10

instance1 = MyClass()
instance2 = MyClass()

# class-level attributes
print(instance1.shared_var)  # Output: 10
print(instance2.shared_var)  # Output: 10

instance1.shared_var = 20
# shared_var is now an instance-level attribute for instance1
# the instance-level modification will not affect other instances
print(instance1.shared_var)  # Output: 20
print(instance2.shared_var)  # Output: 10

MyClass.shared_var = 30
# change of class-level will only explicitly affect the instances that don't have the same-named but instance-level attribute
print(instance1.shared_var)  # Output: 20
print(instance2.shared_var)  # Output: 30---only instance2 is affected

print("After deleting the instance-level attribute")
del instance1.shared_var
# delete the instance-level attribute, unshadow the class-level attribute
print(instance1.shared_var)  # Output: 30---now it's the class-level attribute

10
10
20
10
20
30
After deleting the instance-level attribute
30


In [12]:
"""  
Here we test the usage of __slots__ to restrict the attributes of a class
for memory saving and making the access faster
"""

class myclass:
    __slots__ = ['a', 'b']
    def __init__(self):
        self.a = 1
        self.b = 2
        # self.c = 3 it will raise an error because c is not in __slots__
    def __getitem__(self, key):
        return getattr(self, key)

obj = myclass()
print(obj['a'])
print(obj.a)
obj.a=3      # can modify the attribute
obj.c=4      # can't add new attribute


1
1


AttributeError: 'myclass' object has no attribute 'c'

In [13]:
"""  
Here we test some string operations
"""
# 1. rsplit() method
somepath="/home/username/folder/file.txt"
ss = somepath.rsplit('/', 1)  # split the string from the right side, only once
print(ss)

# 2. match() and fullmatch() methods
import re
pattern = re.compile("abc")
result = pattern.match("abcdef")
# result is a match object since "abcdef" starts with "abc"
result2 = pattern.match("defabc")
# result2 is None because "defabc" does not start with "abc"
print(result, result2)

pattern = re.compile("abc")
result = pattern.fullmatch("abcdef")
# result is None because the entire string "abcdef" does not conform to "abc"
result2 = pattern.fullmatch("abc")
# result2 is a match object because the entire string "abc" perfectly matches "abc"
print(result, result2)

# 3. join() method
vals=['a', 'b', 'c']
vals = 'x '.join(f"'{x}'" for x in vals)
print(vals)

# 4. split() method with maxsplit
sss="abc=1=2=3"
print(sss.split('=', 1))

# 5. non-alphanumeric character check
IS_PATTERN = re.compile(r'.*[^A-Za-z0-9_.-].*')
name = "abc"
print(IS_PATTERN.fullmatch(name))


['/home/username/folder', 'file.txt']
<re.Match object; span=(0, 3), match='abc'> None
None <re.Match object; span=(0, 3), match='abc'>
'a'x 'b'x 'c'
['abc', '1=2=3']
None


In [14]:
"""  
Here we test the usage of the format() method 
for string formatting with placeholders
"""

string_withplace = "Hello {name}, welcome to {place}"
print(string_withplace.format(name="John", place="New York"))

# 2. Using raw strings
print(r"\_")

Hello John, welcome to New York
\_


In [17]:
"""  
Here we test deque
"""
from collections import deque

dq=deque([1,2,3,4,5],maxlen=3)
print(dq)

dq1=deque([1,2,3,4,5],maxlen=5)
dq1.appendleft(dq1.pop()) 
print(dq1)

deque([3, 4, 5], maxlen=3)
deque([5, 1, 2, 3, 4], maxlen=5)


In [45]:
"""  
Here we test the np.mean and np.amax on a deque
"""

buffers = deque(
        [np.zeros((10, 10, 3), np.uint8)+i for i in range(5)],
        maxlen=5)
a=np.mean(buffers, axis=0)
b=np.amax(buffers, axis=0)

# It will output an array with the element-wise mean/maximum of the arrays in the deque
buffers2=deque([np.array([9,2,3]), np.array([4,0,6]), np.array([7,8,9])], maxlen=3)
print(np.mean(buffers2, axis=0))
print(np.amax(buffers2, axis=0))




[6.66666667 3.33333333 6.        ]
[9 8 9]


In [46]:
"""  
Here we see what's the output of np.random.RandomState()
"""
np.random.RandomState()

RandomState(MT19937) at 0x7FEAFD7CAC40

In [64]:
"""  
Here we test np.dtype() with object type and the result of is between objects
"""

import numpy as np

class DataHandler:
    def __init__(self, dtype):
        self._dtype = np.dtype(dtype)
        assert self._dtype is not object, self._dtype  
        assert self._dtype.kind != 'O', self._dtype  # This will raise an error if the dtype is an instance
        # if dtype is an instance, self._dtype is not object, but not the the same object as the built-in Python object type itself
handler = DataHandler('float64')  # Works fine
# handler = DataHandler(myclass)  # Raises AssertionError
handler=  DataHandler(np.float64) # Works fine
print(myclass is object)  # False, not the same object as the built-in Python object type itself
print(obj is myclass)
print(obj is object)
print(myclass is myclass)

class child(myclass):
    pass
print(child is myclass) # False, child is not the same class as parent

False
False
False
True
False


In [70]:
"""  
Here we test the broadcasting of np.array
"""
low=1
shape=(2,3)
np.broadcast_to(low, shape)

low2=np.array([1,2,3])
shape2=(2,5)
# np.broadcast_to(low2, shape2)  # error because the shape is not compatible
shape2=(2,6)
# np.broadcast_to(low2, shape2)  # error because the shape is not compatible
shape2=(2,3)
np.broadcast_to(low2, shape2)  # works fine




array([[1, 2, 3],
       [1, 2, 3]])

In [77]:
"""  
test dtype operations
"""
print(np.issubdtype("float", np.floating))
print(np.issubdtype("f", np.floating))
# print(np.issubdtype("flo", np.floating)) # error
print(np.issubdtype(np.float64, np.floating))

True
True
True


In [87]:
"""  
test all() in empty list/tuple and tuple conversion of np.array
"""
shape=()
print(all(dim and dim > 0 for dim in shape)) # True

shape=(1,2)
print(all(dim and dim > 0 for dim in shape)) # True

shape=(0,2)
print(all(dim and dim > 0 for dim in shape)) # False

xx=np.array([1,2,3])
yy=np.array([[1,2,3],[4,5,6]])
print(hasattr(shape, '__len__'))
print(tuple(xx))
print(tuple(yy))



True
True
False
True
(1, 2, 3)
(array([1, 2, 3]), array([4, 5, 6]))
